name: loader_skeleton
description: A Facebook & Twitter Like Card Loading Shimmer Skeleton Library.
version: 1.0.2
homepage: https://github.com/djade007/skeleton_loader

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: